'use client';
import Link from 'next/link';
import {useEffect,useMemo,useState} from 'react';
import {ShoppingBag,ShieldCheck,Truck,LockKeyhole,Minus,Plus,Trash2} from 'lucide-react';

type CartItem={id:string;name:string;price:number;image?:string|null;qty:number};

export default function CartPage(){
  const [items,setItems]=useState<CartItem[]>([]);
  useEffect(()=>{const raw=localStorage.getItem('vantacart_cart');setItems(raw?JSON.parse(raw):[])},[]);
  function save(next:CartItem[]){setItems(next);localStorage.setItem('vantacart_cart',JSON.stringify(next));window.dispatchEvent(new Event('vantacart-cart-updated'))}
  function change(id:string,delta:number){save(items.map(i=>i.id===id?{...i,qty:Math.max(1,i.qty+delta)}:i))}
  function remove(id:string){save(items.filter(i=>i.id!==id))}
  const subtotal=useMemo(()=>items.reduce((s,i)=>s+i.price*i.qty,0),[items]);
  return <main className="checkoutPage"><header className="checkoutHeader"><Link href="/" className="checkoutLogo">Vanta<span>Cart</span></Link><div className="checkoutSecure"><LockKeyhole size={17}/> Secure checkout preparation</div></header><div className="checkoutShell"><div className="checkoutTitle"><div><h1>Your cart</h1><p>Review your items and destination details before shipping is calculated.</p></div><ShoppingBag size={30}/></div>{items.length===0?<div className="emptyCart"><h2>Your cart is empty</h2><p>Add a product from the VantaCart catalog to continue.</p><Link href="/#shop" className="marketBtnPrimary">Continue shopping</Link></div>:<div className="checkoutGrid"><section><div className="checkoutCard"><h2>Items</h2>{items.map(i=><div className="cartLine" key={i.id}><div className="cartThumb">{i.image?<img src={i.image} alt={i.name}/>:<span>📦</span>}</div><div className="cartMain"><Link href={`/products/${i.id}`}>{i.name}</Link><span>Supplier-linked fulfillment</span><div className="qtyControl"><button onClick={()=>change(i.id,-1)}><Minus size={14}/></button><b>{i.qty}</b><button onClick={()=>change(i.id,1)}><Plus size={14}/></button><button className="removeBtn" onClick={()=>remove(i.id)}><Trash2 size={14}/> Remove</button></div></div><div className="cartPrice">${(i.price*i.qty).toFixed(2)}</div></div>)}</div><div className="checkoutCard"><h2>Delivery destination</h2><div className="addressGrid"><label>Country / Region<select defaultValue=""><option value="" disabled>Select country</option><option>United States</option><option>Canada</option><option>United Kingdom</option><option>Germany</option><option>France</option><option>Italy</option><option>Spain</option><option>Australia</option><option>Brazil</option></select></label><label>Postal code<input placeholder="ZIP / Postal code"/></label><label className="fullField">City<input placeholder="City"/></label><label className="fullField">Address<input placeholder="Street address"/></label></div><div className="shippingPrep"><Truck size={18}/><div><b>Shipping calculation comes next</b><span>We will connect this destination to CJ shipping rates before enabling payment.</span></div></div></div></section><aside className="orderSummary"><h2>Order summary</h2><div className="summaryRow"><span>Items</span><b>${subtotal.toFixed(2)}</b></div><div className="summaryRow"><span>Shipping</span><b>Calculated next</b></div><div className="summaryRow"><span>Taxes & duties</span><b>Destination based</b></div><div className="summaryTotal"><span>Estimated total</span><b>${subtotal.toFixed(2)}</b></div><button className="checkoutDisabled" disabled>Continue to secure payment</button><p>No payment is enabled yet. We are validating shipping, destination costs and supplier fulfillment first.</p><div className="summaryTrust"><span><ShieldCheck size={16}/> Buyer protection flow</span><span><LockKeyhole size={16}/> Payment data handled by processor</span></div></aside></div>}</div></main>
}
