'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { ArrowRight, CheckCircle2, ExternalLink, ShieldCheck, Sparkles, Play, Zap, Users, BarChart3, Bot, Workflow, ChevronDown } from 'lucide-react';

type Campaign={id:string;name:string;advertiser:string;status?:string;trackingLink?:string};
type Slug='creao'|'riibase';

const data={
 riibase:{name:'Riibase',match:'riibase',eyebrow:'CRM • VENDAS • AUTOMAÇÃO',title:'Pare de perder vendas por falta de organização.',accent:'Transforme contatos em clientes.',sub:'Veja como uma operação comercial organizada pode centralizar leads, follow-ups, oportunidades e relacionamento em um único lugar.',cta:'Quero conhecer o Riibase',metrics:[['1 painel','para toda a operação'],['24/7','processos organizados'],['360°','visão do cliente']],features:[[Users,'Clientes no lugar certo','Centralize contatos, histórico e oportunidades sem depender de planilhas espalhadas.'],[Workflow,'Pipeline visual','Acompanhe cada oportunidade e saiba exatamente qual é o próximo passo.'],[Bot,'IA na operação','Ganhe velocidade em tarefas repetitivas e rotinas comerciais.'],[BarChart3,'Decisões mais claras','Tenha uma visão organizada da operação para acompanhar seu crescimento.']]},
 creao:{name:'Creao AI',match:'creao',eyebrow:'IA • AUTOMAÇÃO • PRODUTIVIDADE',title:'Faça a IA trabalhar enquanto você foca no que importa.',accent:'Menos tarefas. Mais resultado.',sub:'Crie agentes, conecte ferramentas e transforme processos repetitivos em fluxos inteligentes dentro de um único ambiente.',cta:'Quero conhecer a Creao AI',metrics:[['1 lugar','para suas automações'],['24/7','agentes trabalhando'],['+ foco','no que gera valor']],features:[[Bot,'Agentes inteligentes','Crie agentes reutilizáveis para executar tarefas e acelerar sua rotina.'],[Workflow,'Fluxos conectados','Integre ferramentas e transforme etapas manuais em automações.'],[Zap,'Execução rápida','Reduza tarefas repetitivas e ganhe tempo para decisões importantes.'],[Sparkles,'Criação com IA','Produza conteúdo e organize trabalho em um ambiente moderno.']]}
} as const;

export default function AffiliateOfferLanding({slug,lang}:{slug:Slug;lang:'pt'|'en'}){
 const d=data[slug]; const [campaign,setCampaign]=useState<Campaign|null>(null); const [loading,setLoading]=useState(true); const [open,setOpen]=useState(0);
 useEffect(()=>{let x=false;fetch('/api/impact/campaigns',{cache:'no-store'}).then(r=>r.json()).then(v=>{if(x||!v?.ok)return;setCampaign(v.campaigns?.find((c:Campaign)=>`${c.name} ${c.advertiser}`.toLowerCase().includes(d.match)&&c.status==='Active'&&c.trackingLink)||null)}).finally(()=>!x&&setLoading(false));return()=>{x=true}},[d.match]);
 const href=campaign?.trackingLink;
 return <main className="offerExperience">
  <div className="offerGlow glowOne"/><div className="offerGlow glowTwo"/>
  <header className="offerNav"><Link href={`/?lang=${lang}`} className="offerLogo">Vanta<span>Cart</span></Link><nav><a href="#beneficios">Benefícios</a><a href="#como">Como funciona</a><Link href={`/?lang=${lang}`}>Outras ofertas</Link></nav><Link className="offerLang" href={`/offers/${slug}?lang=${lang==='pt'?'en':'pt'}`}>{lang==='pt'?'EN':'PT'}</Link></header>
  <section className="offerHero">
   <div className="offerHeroCopy"><div className="offerPill"><span/> {d.eyebrow}</div><h1>{d.title}<br/><em>{d.accent}</em></h1><p>{d.sub}</p><div className="offerCtas">{href?<a className="offerPrimary" href={href} target="_blank" rel="sponsored noopener noreferrer">{d.cta}<ArrowRight/></a>:<button className="offerPrimary" disabled>{loading?'Carregando oferta...':'Oferta indisponível'}</button>}<a className="offerSecondary" href="#como"><Play/> Ver como funciona</a></div><div className="offerTrust"><ShieldCheck/><span><b>Acesso pelo parceiro oficial</b><small>Link rastreado • sem custo adicional</small></span></div></div>
   <div className="offerDemo"><div className="demoTop"><i/><i/><i/><span>{d.name} • workspace</span></div><div className="demoBody"><aside><div className="demoBrand">{slug==='riibase'?'R':'AI'}</div>{[1,2,3,4,5].map(i=><span key={i}/>)}</aside><div className="demoContent"><div className="demoHello"><small>{slug==='riibase'?'VISÃO COMERCIAL':'AUTOMAÇÃO INTELIGENTE'}</small><b>{slug==='riibase'?'Seu negócio, organizado.':'Seu trabalho, acelerado.'}</b></div><div className="demoStats">{d.metrics.map(([a,b])=><div key={a}><strong>{a}</strong><span>{b}</span></div>)}</div><div className="demoBoard"><div><span>01</span><b>{slug==='riibase'?'Novos leads':'Entrada'}</b><i/><i/><i/></div><div><span>02</span><b>{slug==='riibase'?'Em negociação':'Agente IA'}</b><i/><i/></div><div><span>03</span><b>{slug==='riibase'?'Fechados':'Concluído'}</b><i/></div></div></div></div><div className="floatingBadge"><Sparkles/> <span><b>{slug==='riibase'?'Tudo sob controle':'Automação ativa'}</b><small>{slug==='riibase'?'pipeline atualizado':'executando tarefas'}</small></span></div></div>
  </section>
  <section className="socialStrip"><span>✓ Plataforma oficial</span><span>✓ Processo simples</span><span>✓ Ambiente profissional</span><span>✓ Acesso seguro</span></section>
  <section className="offerBenefits" id="beneficios"><div className="offerSectionHead"><span>POR QUE USAR</span><h2>Uma experiência feita para transformar<br/>complexidade em <em>simplicidade.</em></h2></div><div className="offerFeatureGrid">{d.features.map(([Icon,title,text],i)=><article key={title} className="offerFeature"><div className="featureNum">0{i+1}</div><Icon/><h3>{title}</h3><p>{text}</p><a href={href||'#'} target={href?'_blank':undefined}>Explorar <ArrowRight/></a></article>)}</div></section>
  <section className="offerHow" id="como"><div><span className="offerPill">EXPERIÊNCIA SEM COMPLICAÇÃO</span><h2>Do interesse à ação<br/>em poucos passos.</h2><p>Você conhece a solução aqui e, quando estiver pronto, continua diretamente no ambiente oficial do parceiro.</p></div><div className="steps">{[['01','Descubra','Entenda rapidamente como a solução pode ajudar sua rotina.'],['02','Explore','Acesse recursos, demonstrações e condições no site oficial.'],['03','Comece','Escolha o plano adequado e coloque a solução para trabalhar.']].map(x=><div key={x[0]}><b>{x[0]}</b><span><strong>{x[1]}</strong><small>{x[2]}</small></span></div>)}</div></section>
  <section className="offerFaq"><h2>Antes de continuar</h2>{[['A compra acontece na VantaCart?','Não. Você é direcionado ao ambiente oficial do parceiro para contratação e pagamento.'],['Existe custo adicional pela indicação?','Não. A indicação não acrescenta custo ao preço apresentado pelo parceiro.'],['O link é rastreado?','Sim. Quando disponível, utilizamos o link oficial do programa de afiliados para registrar a indicação.']].map((q,i)=><button key={q[0]} onClick={()=>setOpen(open===i?-1:i)}><span><b>{q[0]}</b>{open===i&&<p>{q[1]}</p>}</span><ChevronDown className={open===i?'rot':''}/></button>)}</section>
  <section className="offerFinal"><div><span>PRONTO PARA EXPLORAR?</span><h2>{slug==='riibase'?'Dê ao seu comercial uma operação à altura do seu crescimento.':'Coloque a IA para trabalhar a favor da sua produtividade.'}</h2></div>{href&&<a href={href} target="_blank" rel="sponsored noopener noreferrer">{d.cta}<ExternalLink/></a>}</section>
  <footer className="offerFooter"><Link href={`/?lang=${lang}`} className="offerLogo">Vanta<span>Cart</span></Link><p>Descubra. Compare. Escolha melhor.</p><small>Alguns links são de afiliados. Podemos receber comissão sem custo adicional para você.</small></footer>
 </main>
}