'use client';

import Link from 'next/link';
import { ArrowRight, CheckCircle2, ExternalLink, Languages, ShieldCheck, Sparkles, Zap, Target, BadgeCheck } from 'lucide-react';
import { trackEvent } from './Analytics';

type Lang='pt'|'en';
export type GenericImpactCampaign={id:string;name:string;advertiser:string;description?:string;url?:string;status?:string;trackingLink?:string;type?:string;allowsDeeplinking?:string};

type Profile={eyebrowPt:string;eyebrowEn:string;summaryPt:string;summaryEn:string;benefitsPt:string[];benefitsEn:string[]};

function profileFor(c:GenericImpactCampaign):Profile{
  const s=`${c.name} ${c.advertiser}`.toLowerCase();
  const custom:[RegExp,Profile][]=[
    [/gearup for mobile/,{eyebrowPt:'GAMING MOBILE • PERFORMANCE',eyebrowEn:'MOBILE GAMING • PERFORMANCE',summaryPt:'Reduza lag, ping e perda de pacotes em jogos mobile com uma solução criada para conexões mais estáveis e partidas mais fluidas.',summaryEn:'Reduce lag, ping and packet loss in mobile games with a solution built for more stable connections and smoother play.',benefitsPt:['Aceleração para jogos mobile','Foco em estabilidade de conexão','Compatível com milhares de jogos'],benefitsEn:['Mobile game acceleration','Connection stability focus','Built for thousands of games']}],
    [/\bgearup\b/,{eyebrowPt:'GAMING • NETWORK BOOSTER',eyebrowEn:'GAMING • NETWORK BOOSTER',summaryPt:'Otimize sua rota de conexão para jogos e reduza problemas como ping alto, jitter e perda de pacotes durante partidas online.',summaryEn:'Optimize your gaming connection route and reduce issues such as high ping, jitter and packet loss during online play.',benefitsPt:['Menos lag e jitter','Rotas otimizadas para gaming','Experiência focada em desempenho'],benefitsEn:['Lower lag and jitter','Gaming-optimized routes','Performance-focused experience']}],
    [/movavi/,{eyebrowPt:'VÍDEO • CRIAÇÃO • MULTIMÍDIA',eyebrowEn:'VIDEO • CREATION • MULTIMEDIA',summaryPt:'Crie e edite vídeos, imagens e conteúdo multimídia com ferramentas consolidadas para criadores, profissionais e pequenas empresas.',summaryEn:'Create and edit video, images and multimedia content with established tools for creators, professionals and small businesses.',benefitsPt:['Edição de vídeo acessível','Ferramentas para criadores','Ecossistema multimídia completo'],benefitsEn:['Accessible video editing','Tools for creators','Complete multimedia ecosystem']}],
    [/pixverse/,{eyebrowPt:'IA • VÍDEO GENERATIVO',eyebrowEn:'AI • GENERATIVE VIDEO',summaryPt:'Transforme ideias, imagens e prompts em vídeos gerados por IA para conteúdo social, campanhas e criação visual.',summaryEn:'Turn ideas, images and prompts into AI-generated videos for social content, campaigns and visual creation.',benefitsPt:['Vídeo gerado por IA','Criação rápida de conteúdo','Fluxo simples para criadores'],benefitsEn:['AI-generated video','Fast content creation','Simple creator workflow']}],
    [/shengshu|vidu/,{eyebrowPt:'IA • STORYTELLING EM VÍDEO',eyebrowEn:'AI • VIDEO STORYTELLING',summaryPt:'Gere vídeos com IA a partir de texto, imagens e referências, mantendo consistência visual entre personagens, objetos e cenas.',summaryEn:'Generate AI video from text, images and references while preserving visual consistency across characters, objects and scenes.',benefitsPt:['Texto e imagem para vídeo','Consistência entre cenas','Criação visual com IA'],benefitsEn:['Text and image to video','Cross-scene consistency','AI visual creation']}],
    [/wizstar/,{eyebrowPt:'IA • VÍDEO PARA MARKETING',eyebrowEn:'AI • VIDEO FOR MARKETING',summaryPt:'Transforme links de produtos, imagens e ideias em vídeos, traduza conteúdo e adapte campanhas para diferentes públicos.',summaryEn:'Turn product links, images and ideas into video, translate content and adapt campaigns for different audiences.',benefitsPt:['Vídeos para e-commerce','Tradução e localização','Automação para criadores'],benefitsEn:['E-commerce video','Translation and localization','Creator automation']}],
    [/creao/,{eyebrowPt:'IA • AGENTES • AUTOMAÇÃO',eyebrowEn:'AI • AGENTS • AUTOMATION',summaryPt:'Crie agentes e aplicativos de IA reutilizáveis, conecte ferramentas e automatize tarefas em um único ambiente de trabalho.',summaryEn:'Build reusable AI agents and apps, connect your tools and automate tasks from one workspace.',benefitsPt:['Agentes de IA reutilizáveis','Integração com ferramentas','Automação de tarefas'],benefitsEn:['Reusable AI agents','Tool integrations','Task automation']}],
    [/riibase/,{eyebrowPt:'CRM • NEGÓCIOS • IA',eyebrowEn:'CRM • BUSINESS • AI',summaryPt:'Centralize relacionamento com clientes, vendas e operações em um CRM completo com recursos de IA integrados.',summaryEn:'Centralize customer relationships, sales and operations in an all-in-one CRM with built-in AI capabilities.',benefitsPt:['CRM tudo em um','Recursos de IA integrados','Gestão comercial centralizada'],benefitsEn:['All-in-one CRM','Built-in AI features','Centralized sales management']}],
    [/protoarc/,{eyebrowPt:'ERGONOMIA • HOME OFFICE',eyebrowEn:'ERGONOMICS • HOME OFFICE',summaryPt:'Melhore conforto e produtividade no escritório ou home office com periféricos e acessórios ergonômicos para longas jornadas.',summaryEn:'Improve comfort and productivity at the office or home workspace with ergonomic peripherals and accessories for long sessions.',benefitsPt:['Ergonomia para o dia a dia','Periféricos para home office','Mais conforto no trabalho'],benefitsEn:['Everyday ergonomics','Home-office peripherals','More work comfort']}],
    [/gamsgo/,{eyebrowPt:'ASSINATURAS • DIGITAL',eyebrowEn:'SUBSCRIPTIONS • DIGITAL',summaryPt:'Encontre assinaturas digitais, IA, streaming e gaming em uma plataforma voltada a acesso rápido e economia.',summaryEn:'Discover digital subscriptions, AI, streaming and gaming in a platform focused on fast access and savings.',benefitsPt:['Diversas assinaturas digitais','Acesso rápido','Categorias de IA, streaming e games'],benefitsEn:['Multiple digital subscriptions','Fast access','AI, streaming and gaming categories']}],
    [/appy pie/,{eyebrowPt:'IA • APP BUILDER • NO-CODE',eyebrowEn:'AI • APP BUILDER • NO-CODE',summaryPt:'Crie aplicativos móveis e web a partir de instruções simples, sem precisar desenvolver toda a infraestrutura manualmente.',summaryEn:'Create mobile and web apps from simple instructions without manually building the entire infrastructure.',benefitsPt:['Criação sem código','Apps web e mobile','Automação de backend e design'],benefitsEn:['No-code creation','Web and mobile apps','Automated backend and design']}],
    [/\bmedo\b/,{eyebrowPt:'IA • APP BUILDER',eyebrowEn:'AI • APP BUILDER',summaryPt:'Transforme uma ideia em aplicativo com geração assistida por IA e fluxo sem código para acelerar protótipos e lançamentos.',summaryEn:'Turn an idea into an app with AI-assisted generation and a no-code flow designed to speed up prototypes and launches.',benefitsPt:['Ideia para app com IA','Sem necessidade de código','Prototipação rápida'],benefitsEn:['Idea-to-app with AI','No coding required','Fast prototyping']}],
    [/lorka/,{eyebrowPt:'IA • PRODUTIVIDADE • CRIAÇÃO',eyebrowEn:'AI • PRODUCTIVITY • CREATION',summaryPt:'Reúna diferentes recursos de IA em uma suíte única para criação, produtividade e tarefas de marketing.',summaryEn:'Bring multiple AI capabilities into one suite for creation, productivity and marketing tasks.',benefitsPt:['Suíte de IA integrada','Ferramentas para marketing','Produtividade em um só lugar'],benefitsEn:['Integrated AI suite','Marketing tools','Productivity in one place']}],
    [/verdent/,{eyebrowPt:'IA • DESENVOLVIMENTO DE SOFTWARE',eyebrowEn:'AI • SOFTWARE DEVELOPMENT',summaryPt:'Acelere desenvolvimento de software, criação de aplicativos e automações com uma plataforma de construção assistida por IA.',summaryEn:'Accelerate software development, app creation and automation with an AI-assisted building platform.',benefitsPt:['Desenvolvimento com IA','Criação de aplicações','Automação de trabalho'],benefitsEn:['AI development','Application building','Work automation']}],
    [/accio/,{eyebrowPt:'B2B • SOURCING • IA',eyebrowEn:'B2B • SOURCING • AI',summaryPt:'Pesquise, compare e desenvolva produtos com apoio de IA, conectando oportunidades a fornecedores e plataformas de comércio.',summaryEn:'Research, compare and develop products with AI support while connecting opportunities to suppliers and commerce platforms.',benefitsPt:['Pesquisa de fornecedores','Comparação de produtos','Apoio de IA para sourcing'],benefitsEn:['Supplier research','Product comparison','AI-assisted sourcing']}],
    [/presentation intelligence|deepvinci/,{eyebrowPt:'APRESENTAÇÕES • IA • PRODUTIVIDADE',eyebrowEn:'PRESENTATIONS • AI • PRODUCTIVITY',summaryPt:'Use inteligência aplicada a apresentações para estruturar conteúdo visual de forma mais rápida e profissional.',summaryEn:'Use presentation intelligence to structure visual content faster and more professionally.',benefitsPt:['Apresentações mais rápidas','Assistência inteligente','Fluxo visual profissional'],benefitsEn:['Faster presentations','Intelligent assistance','Professional visual workflow']}]
  ];
  const found=custom.find(([re])=>re.test(s));if(found)return found[1];
  return {eyebrowPt:'TECNOLOGIA • OFERTA VERIFICADA',eyebrowEn:'TECHNOLOGY • VERIFIED OFFER',summaryPt:c.description||'Conheça esta solução de um parceiro aprovado e ativo no ecossistema VantaCart.',summaryEn:c.description||'Explore this solution from an approved, active VantaCart partner.',benefitsPt:['Parceiro verificado','Acesso direto ao fornecedor','Oferta sincronizada pela Impact'],benefitsEn:['Verified partner','Direct partner access','Impact-synchronized offer']};
}

export default function GenericImpactOfferLanding({campaign,lang,slug}:{campaign:GenericImpactCampaign;lang:Lang;slug:string}){
  const pt=lang==='pt';const profile=profileFor(campaign);
  const cta=pt?'Ver oferta no site oficial':'View official offer';
  const description=pt?profile.summaryPt:profile.summaryEn;
  const benefits=pt?profile.benefitsPt:profile.benefitsEn;
  const eyebrow=pt?profile.eyebrowPt:profile.eyebrowEn;
  const go=()=>{trackEvent('affiliate_click',{partner:campaign.advertiser,offer_name:campaign.name,campaign_id:campaign.id,language:lang,destination:'impact_tracking_link'});trackEvent('affiliate_outbound_click',{partner:campaign.advertiser,offer_name:campaign.name,campaign_id:campaign.id,language:lang,destination:'impact_tracking_link'});};

  return <main className="genericOffer" style={{minHeight:'100vh',background:'#f4f7f4',color:'#0b1711',fontFamily:'Arial,Helvetica,sans-serif'}}>
    <header style={{position:'sticky',top:0,zIndex:20,background:'rgba(244,247,244,.92)',backdropFilter:'blur(16px)',borderBottom:'1px solid #dde6df'}}><div style={{maxWidth:1180,margin:'auto',padding:'16px 22px',display:'flex',alignItems:'center',justifyContent:'space-between',gap:18}}><Link href={`/?lang=${lang}`} style={{fontSize:26,fontWeight:900,color:'#07130d',textDecoration:'none',letterSpacing:'-1.4px'}}>Vanta<span style={{color:'#23d56f'}}>Cart</span></Link><Link href={`/offers/${slug}?lang=${pt?'en':'pt'}`} style={{display:'flex',gap:7,alignItems:'center',padding:'10px 14px',border:'1px solid #d4dfd7',borderRadius:999,textDecoration:'none',color:'#183326',background:'#fff',fontWeight:800}}><Languages size={16}/>{pt?'EN':'PT'}</Link></div></header>

    <section style={{maxWidth:1180,margin:'30px auto 0',padding:'0 22px'}}><div style={{position:'relative',overflow:'hidden',borderRadius:34,background:'radial-gradient(circle at 86% 15%,rgba(78,242,143,.28),transparent 24%),linear-gradient(125deg,#07130d,#10331f 68%,#185237)',color:'#fff',padding:'70px 64px',boxShadow:'0 32px 85px rgba(7,30,17,.18)'}}><div style={{maxWidth:760,position:'relative',zIndex:2}}><div style={{display:'inline-flex',alignItems:'center',gap:8,border:'1px solid rgba(115,255,166,.28)',background:'rgba(72,236,129,.08)',padding:'9px 13px',borderRadius:999,color:'#a9f6c2',fontSize:12,fontWeight:900,letterSpacing:.7}}><CheckCircle2 size={15}/>{pt?'PARCEIRO IMPACT ATIVO':'ACTIVE IMPACT PARTNER'}</div><p style={{margin:'18px 0 8px',color:'#8eeeb1',fontWeight:900,fontSize:12,letterSpacing:1.25}}>{eyebrow}</p><h1 style={{fontSize:'clamp(44px,7vw,78px)',lineHeight:.96,letterSpacing:'-3.5px',margin:'0 0 22px'}}>{campaign.name}</h1><p style={{fontSize:18,lineHeight:1.65,color:'#c7d9ce',maxWidth:720}}>{description}</p><div style={{display:'flex',gap:12,flexWrap:'wrap',marginTop:30}}><a href={campaign.trackingLink} target="_blank" rel="sponsored noopener noreferrer" onClick={go} style={{display:'inline-flex',alignItems:'center',gap:9,padding:'15px 19px',borderRadius:13,background:'#54ed91',color:'#06140c',fontWeight:900,textDecoration:'none'}}>{cta}<ArrowRight size={19}/></a>{campaign.url&&<a href={campaign.url} target="_blank" rel="noopener noreferrer" style={{display:'inline-flex',alignItems:'center',gap:8,padding:'15px 19px',borderRadius:13,border:'1px solid rgba(255,255,255,.18)',color:'#fff',textDecoration:'none',fontWeight:800}}>{pt?'Conhecer a marca':'Visit brand'}<ExternalLink size={16}/></a>}</div><div style={{display:'flex',alignItems:'center',gap:10,marginTop:25,color:'#a9beb2',fontSize:12}}><ShieldCheck size={18}/><span>{pt?'Link oficial rastreado pela Impact • sem custo adicional para você':'Official Impact tracked link • no extra cost to you'}</span></div></div></div></section>

    <section style={{maxWidth:1180,margin:'24px auto 0',padding:'0 22px'}}><div style={{background:'#fff',border:'1px solid #dfe8e2',borderRadius:24,padding:'26px 28px'}}><div style={{display:'flex',alignItems:'center',gap:9,color:'#166534',fontWeight:900,fontSize:12,letterSpacing:.7}}><Target size={18}/>{pt?'POR QUE CONSIDERAR ESTA SOLUÇÃO':'WHY CONSIDER THIS SOLUTION'}</div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(210px,1fr))',gap:12,marginTop:18}}>{benefits.map((b,i)=><div key={b} style={{border:'1px solid #e4ebe6',borderRadius:16,padding:'18px 18px',background:'#fbfdfb'}}><BadgeCheck size={20} color="#18a957"/><b style={{display:'block',fontSize:14,marginTop:11}}>{b}</b><span style={{display:'block',fontSize:11,color:'#718178',marginTop:5,lineHeight:1.45}}>{pt?['Uso prático no dia a dia','Acesso ao ambiente oficial','Oferta disponível enquanto o programa estiver ativo'][i%3]:['Practical everyday use','Access to the official environment','Available while the program remains active'][i%3]}</span></div>)}</div></div></section>

    <section style={{maxWidth:1180,margin:'16px auto',padding:'0 22px',display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:14}}>{[[CheckCircle2,pt?'Programa ativo':'Active program',pt?'A página é exibida apenas enquanto o contrato estiver ativo e com link de rastreamento válido.':'This page is displayed only while the contract is active and has a valid tracking link.'],[ShieldCheck,pt?'Compra no parceiro':'Purchase with partner',pt?'A contratação ou compra acontece diretamente no site oficial do parceiro.':'Purchase or signup happens directly on the partner’s official website.'],[Zap,pt?'Atualização automática':'Automatic updates',pt?'Novos parceiros ativos entram na vitrine automaticamente por meio da integração com a Impact.':'New active partners are automatically surfaced through the Impact integration.'],[Sparkles,pt?'Curadoria VantaCart':'VantaCart curation',pt?'A VantaCart organiza as soluções para facilitar descoberta, comparação e decisão.':'VantaCart organizes solutions to make discovery, comparison and decisions easier.']].map(([Icon,title,text]:any)=><article key={title} style={{background:'#fff',border:'1px solid #dfe8e2',borderRadius:22,padding:24,boxShadow:'0 12px 30px rgba(8,35,19,.04)'}}><Icon size={24} color="#18a957"/><h2 style={{fontSize:18,margin:'18px 0 8px'}}>{title}</h2><p style={{fontSize:13,lineHeight:1.55,color:'#6b7e73',margin:0}}>{text}</p></article>)}</section>

    <section style={{maxWidth:1180,margin:'26px auto 70px',padding:'0 22px'}}><div style={{borderRadius:28,background:'#0b1c13',color:'#fff',padding:'40px',display:'flex',alignItems:'center',justifyContent:'space-between',gap:26,flexWrap:'wrap'}}><div><div style={{color:'#74efa2',fontSize:12,fontWeight:900,letterSpacing:1}}>{pt?'CONFIRA DIRETAMENTE NO PARCEIRO':'CHECK IT DIRECTLY WITH THE PARTNER'}</div><h2 style={{fontSize:34,letterSpacing:'-1.7px',margin:'8px 0 6px'}}>{campaign.name}</h2><p style={{color:'#a9beb2',margin:0}}>{pt?'Veja preços, planos, recursos e condições atualizadas no ambiente oficial.':'See current pricing, plans, features and terms in the official environment.'}</p></div><a href={campaign.trackingLink} target="_blank" rel="sponsored noopener noreferrer" onClick={go} style={{display:'inline-flex',alignItems:'center',gap:9,padding:'15px 19px',borderRadius:13,background:'#54ed91',color:'#06140c',fontWeight:900,textDecoration:'none'}}>{cta}<ArrowRight size={19}/></a></div><p style={{fontSize:11,color:'#718178',lineHeight:1.6,marginTop:18}}>{pt?'Divulgação: alguns links da VantaCart são links de afiliados. Podemos receber comissão quando você contrata ou compra pelo link, sem custo adicional para você.':'Disclosure: some VantaCart links are affiliate links. We may earn a commission when you purchase or sign up through them, at no extra cost to you.'}</p></section>
  </main>;
}
