'use client';

import Link from 'next/link';
import { ArrowRight, CheckCircle2, Languages, ShieldCheck, Target, BadgeCheck, WalletCards } from 'lucide-react';
import { trackEvent } from './Analytics';

type Lang='pt'|'en';
type PricingType='fixed'|'from'|'range'|'plans'|'unknown';
export type HotmartOfferCampaign={id:string;name:string;advertiser:string;description?:string;trackingLink:string;category?:string;price?:number;priceFrom?:number;priceMax?:number;currency?:string;pricingType?:PricingType;lastPriceCheck?:string;priceNote?:string};
function money(value:number,currency='BRL',lang:Lang='pt'){try{return new Intl.NumberFormat(lang==='pt'?'pt-BR':'en-US',{style:'currency',currency}).format(value);}catch{return `${currency} ${value.toFixed(2)}`;}}
function pricingLabel(c:HotmartOfferCampaign,lang:Lang){const currency=c.currency||'BRL';if(c.pricingType==='fixed'&&typeof c.price==='number')return money(c.price,currency,lang);if(c.pricingType==='from'&&typeof c.priceFrom==='number')return `${lang==='pt'?'A partir de':'From'} ${money(c.priceFrom,currency,lang)}`;if(c.pricingType==='range'&&typeof c.priceFrom==='number'&&typeof c.priceMax==='number')return `${money(c.priceFrom,currency,lang)} – ${money(c.priceMax,currency,lang)}`;if(c.pricingType==='plans')return lang==='pt'?'Planos e condições disponíveis no site oficial':'Plans and conditions available on the official site';return lang==='pt'?'Consulte o preço atual no site oficial':'Check current pricing on the official site';}

export default function GenericHotmartOfferLanding({campaign,lang,slug}:{campaign:HotmartOfferCampaign;lang:Lang;slug:string}){
  const pt=lang==='pt';
  const go=()=>{trackEvent('affiliate_click',{partner:campaign.advertiser,offer_name:campaign.name,campaign_id:campaign.id,network:'hotmart',language:lang,destination:'hotmart_tracking_link'});trackEvent('affiliate_outbound_click',{partner:campaign.advertiser,offer_name:campaign.name,campaign_id:campaign.id,network:'hotmart',language:lang,destination:'hotmart_tracking_link'});};
  const benefits=pt?['Parceiro afiliado ativo','Hotlink oficial da Hotmart','Compra concluída no ambiente do produtor']:['Active affiliate partner','Official Hotmart tracking link','Purchase completed with the producer'];
  return <main style={{minHeight:'100vh',background:'#f4f7f4',color:'#0b1711',fontFamily:'Arial,Helvetica,sans-serif'}}>
    <header style={{position:'sticky',top:0,zIndex:20,background:'rgba(244,247,244,.92)',borderBottom:'1px solid #dde6df'}}><div style={{maxWidth:1180,margin:'auto',padding:'16px 22px',display:'flex',justifyContent:'space-between',alignItems:'center'}}><Link href={`/?lang=${lang}`} style={{fontSize:26,fontWeight:900,color:'#07130d',textDecoration:'none'}}>Vanta<span style={{color:'#23d56f'}}>Cart</span></Link><Link href={`/offers/${slug}?lang=${pt?'en':'pt'}`} style={{display:'flex',gap:7,alignItems:'center',padding:'10px 14px',border:'1px solid #d4dfd7',borderRadius:999,textDecoration:'none',color:'#183326',background:'#fff',fontWeight:800}}><Languages size={16}/>{pt?'EN':'PT'}</Link></div></header>
    <section style={{maxWidth:1180,margin:'30px auto 0',padding:'0 22px'}}><div style={{borderRadius:34,background:'linear-gradient(125deg,#07130d,#10331f 68%,#185237)',color:'#fff',padding:'70px 64px'}}><div style={{maxWidth:760}}><div style={{display:'inline-flex',alignItems:'center',gap:8,border:'1px solid rgba(115,255,166,.28)',padding:'9px 13px',borderRadius:999,color:'#a9f6c2',fontSize:12,fontWeight:900}}><CheckCircle2 size={15}/>{pt?'PARCEIRO HOTMART ATIVO':'ACTIVE HOTMART PARTNER'}</div><p style={{margin:'18px 0 8px',color:'#8eeeb1',fontWeight:900,fontSize:12,letterSpacing:1.25}}>{(campaign.category||'OFERTA DIGITAL').toUpperCase()}</p><h1 style={{fontSize:'clamp(44px,7vw,78px)',lineHeight:.96,letterSpacing:'-3.5px',margin:'0 0 22px'}}>{campaign.name}</h1><p style={{fontSize:18,lineHeight:1.65,color:'#c7d9ce',maxWidth:720}}>{campaign.description|| (pt?'Conheça esta oferta digital de um parceiro afiliado ativo na Hotmart.':'Explore this digital offer from an active Hotmart affiliate partner.')}</p><div style={{marginTop:22,display:'inline-flex',alignItems:'center',gap:10,padding:'12px 14px',border:'1px solid rgba(255,255,255,.14)',borderRadius:14,background:'rgba(255,255,255,.06)'}}><WalletCards size={18}/><div><span style={{display:'block',fontSize:10,fontWeight:900,letterSpacing:1,color:'#9ddbb5'}}>{pt?'PREÇO / PLANOS':'PRICE / PLANS'}</span><strong style={{fontSize:15}}>{pricingLabel(campaign,lang)}</strong>{campaign.priceNote?<span style={{display:'block',marginTop:3,fontSize:11,color:'#b6c9bd'}}>{campaign.priceNote}</span>:null}</div></div><br/><a href={campaign.trackingLink} target="_blank" rel="sponsored noopener noreferrer" onClick={go} style={{display:'inline-flex',alignItems:'center',gap:9,marginTop:22,padding:'15px 19px',borderRadius:13,background:'#54ed91',color:'#06140c',fontWeight:900,textDecoration:'none'}}>{pt?'Ver oferta e preço atual':'View offer & current pricing'}<ArrowRight size={19}/></a><div style={{display:'flex',alignItems:'center',gap:10,marginTop:25,color:'#a9beb2',fontSize:12}}><ShieldCheck size={18}/><span>{pt?'Hotlink oficial rastreado pela Hotmart • preços e condições finais são definidos pelo produtor':'Official Hotmart tracked link • final pricing and conditions are set by the producer'}</span></div></div></div></section>
    <section style={{maxWidth:1180,margin:'24px auto 70px',padding:'0 22px'}}><div style={{background:'#fff',border:'1px solid #dfe8e2',borderRadius:24,padding:'26px 28px'}}><div style={{display:'flex',alignItems:'center',gap:9,color:'#166534',fontWeight:900,fontSize:12}}><Target size={18}/>{pt?'POR QUE CONSIDERAR ESTA SOLUÇÃO':'WHY CONSIDER THIS SOLUTION'}</div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(210px,1fr))',gap:12,marginTop:18}}>{benefits.map(b=><div key={b} style={{border:'1px solid #e4ebe6',borderRadius:16,padding:18,background:'#fbfdfb'}}><BadgeCheck size={20} color="#18a957"/><b style={{display:'block',fontSize:14,marginTop:11}}>{b}</b></div>)}</div></div></section>
  </main>;
}
