import { notFound } from 'next/navigation';
import GenericImpactOfferLanding, { GenericImpactCampaign } from '../../components/GenericImpactOfferLanding';
import GenericHotmartOfferLanding from '../../components/GenericHotmartOfferLanding';
import { getHotmartAffiliateOffers } from '../../../lib/hotmart';

export const dynamic='force-dynamic';
type Lang='pt'|'en';
const confirmedTrackingLinks:[RegExp,string][]=[[/gearup for mobile/i,'https://gearupapp.pxf.io/WOPvnP'],[/\bgearup\b/i,'https://gearup.sjv.io/qWGL75'],[/movavi/i,'https://movaviaffiliateprogram.sjv.io/E0YgmP'],[/domoai/i,'https://domoaipteltd.pxf.io/xJqMVy'],[/base44/i,'https://base44.pxf.io/c/7638042/2049275/25619?trafcat=lp']];
function authHeader(accountSid:string,authToken:string){return `Basic ${Buffer.from(`${accountSid}:${authToken}`).toString('base64')}`;}
function slugify(value:string){return value.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');}
function withConfirmedTrackingLink(campaign:GenericImpactCampaign):GenericImpactCampaign{const name=`${campaign.name} ${campaign.advertiser}`;const override=confirmedTrackingLinks.find(([pattern])=>pattern.test(name));return override?{...campaign,trackingLink:override[1]}:campaign;}
function metaContent(html:string,patterns:RegExp[]){for(const pattern of patterns){const match=html.match(pattern);if(match?.[1])return match[1].replace(/&amp;/g,'&').trim();}return null;}
async function resolvePromoImage(source?:string){if(!source)return null;try{const response=await fetch(source,{redirect:'follow',headers:{'user-agent':'Mozilla/5.0 VantaCart/1.0','accept':'text/html,application/xhtml+xml'},signal:AbortSignal.timeout(5000),next:{revalidate:21600}});if(!response.ok)return null;const type=response.headers.get('content-type')||'';if(!type.includes('text/html'))return null;const html=(await response.text()).slice(0,500000);const raw=metaContent(html,[/<meta[^>]+property=["']og:image(?::secure_url)?["'][^>]+content=["']([^"']+)["'][^>]*>/i,/<meta[^>]+content=["']([^"']+)["'][^>]+property=["']og:image(?::secure_url)?["'][^>]*>/i,/<meta[^>]+name=["']twitter:image["'][^>]+content=["']([^"']+)["'][^>]*>/i,/<link[^>]+rel=["']image_src["'][^>]+href=["']([^"']+)["'][^>]*>/i]);if(!raw)return null;const absolute=new URL(raw,response.url).toString();return /^https?:\/\//i.test(absolute)?absolute:null;}catch{return null;}}
async function getImpactCampaigns():Promise<GenericImpactCampaign[]>{const accountSid=process.env.IMPACT_ACCOUNT_SID;const authToken=process.env.IMPACT_AUTH_TOKEN;if(!accountSid||!authToken)return [];const endpoint=`https://api.impact.com/Mediapartners/${encodeURIComponent(accountSid)}/Campaigns.json?PageSize=100`;const response=await fetch(endpoint,{headers:{Authorization:authHeader(accountSid,authToken),Accept:'application/json'},cache:'no-store'});if(!response.ok)return [];const data=await response.json();const campaigns=Array.isArray(data?.Campaigns)?data.Campaigns:[];return campaigns.map((campaign:any)=>withConfirmedTrackingLink({id:campaign.CampaignId,name:campaign.CampaignName,advertiser:campaign.AdvertiserName,description:campaign.CampaignDescription,url:campaign.CampaignUrl,status:campaign.ContractStatus,trackingLink:campaign.TrackingLink,allowsDeeplinking:campaign.AllowsDeeplinking,type:campaign.Type}));}
export default async function AutomaticOffer({params,searchParams}:{params:Promise<{slug:string}>;searchParams:Promise<{lang?:string}>}){const [{slug},sp,impact]=await Promise.all([params,searchParams,getImpactCampaigns()]);const lang:Lang=sp?.lang==='en'?'en':'pt';const hotmart=getHotmartAffiliateOffers().find(o=>o.active&&slugify(o.name)===slug);if(hotmart){const imageUrl=await resolvePromoImage(hotmart.hotlink);return <GenericHotmartOfferLanding campaign={{id:`hotmart-${hotmart.id}`,name:hotmart.name,advertiser:hotmart.producer||hotmart.name,description:hotmart.description,trackingLink:hotmart.hotlink,category:hotmart.category,price:hotmart.price,priceFrom:hotmart.priceFrom,priceMax:hotmart.priceMax,currency:hotmart.currency,pricingType:hotmart.pricingType,lastPriceCheck:hotmart.lastPriceCheck,priceNote:hotmart.priceNote,imageUrl:imageUrl||undefined}} lang={lang} slug={slug}/>;}const campaign=impact.find(c=>c.status==='Active'&&c.trackingLink&&slugify(c.name)===slug);if(!campaign)notFound();const imageUrl=await resolvePromoImage(campaign.url||campaign.trackingLink);return <GenericImpactOfferLanding campaign={{...campaign,imageUrl:imageUrl||undefined}} lang={lang} slug={slug}/>;}
