import { notFound } from 'next/navigation';
import GenericImpactOfferLanding, { GenericImpactCampaign } from '../../components/GenericImpactOfferLanding';
import GenericHotmartOfferLanding from '../../components/GenericHotmartOfferLanding';
import { getHotmartAffiliateOffers } from '../../../lib/hotmart';

export const dynamic='force-dynamic';
type Lang='pt'|'en';
const confirmedTrackingLinks:[RegExp,string][]=[[/gearup for mobile/i,'https://gearupapp.pxf.io/WOPvnP'],[/\bgearup\b/i,'https://gearup.sjv.io/qWGL75'],[/movavi/i,'https://movaviaffiliateprogram.sjv.io/E0YgmP']];
function authHeader(accountSid:string,authToken:string){return `Basic ${Buffer.from(`${accountSid}:${authToken}`).toString('base64')}`;}
function slugify(value:string){return value.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');}
function withConfirmedTrackingLink(campaign:GenericImpactCampaign):GenericImpactCampaign{const name=`${campaign.name} ${campaign.advertiser}`;const override=confirmedTrackingLinks.find(([pattern])=>pattern.test(name));return override?{...campaign,trackingLink:override[1]}:campaign;}
async function getImpactCampaigns():Promise<GenericImpactCampaign[]>{const accountSid=process.env.IMPACT_ACCOUNT_SID;const authToken=process.env.IMPACT_AUTH_TOKEN;if(!accountSid||!authToken)return [];const endpoint=`https://api.impact.com/Mediapartners/${encodeURIComponent(accountSid)}/Campaigns.json?PageSize=100`;const response=await fetch(endpoint,{headers:{Authorization:authHeader(accountSid,authToken),Accept:'application/json'},cache:'no-store'});if(!response.ok)return [];const data=await response.json();const campaigns=Array.isArray(data?.Campaigns)?data.Campaigns:[];return campaigns.map((campaign:any)=>withConfirmedTrackingLink({id:campaign.CampaignId,name:campaign.CampaignName,advertiser:campaign.AdvertiserName,description:campaign.CampaignDescription,url:campaign.CampaignUrl,status:campaign.ContractStatus,trackingLink:campaign.TrackingLink,allowsDeeplinking:campaign.AllowsDeeplinking,type:campaign.Type}));}
export default async function AutomaticOffer({params,searchParams}:{params:Promise<{slug:string}>;searchParams:Promise<{lang?:string}>}){const [{slug},sp,impact]=await Promise.all([params,searchParams,getImpactCampaigns()]);const lang:Lang=sp?.lang==='en'?'en':'pt';const hotmart=getHotmartAffiliateOffers().find(o=>o.active&&slugify(o.name)===slug);if(hotmart){return <GenericHotmartOfferLanding campaign={{id:`hotmart-${hotmart.id}`,name:hotmart.name,advertiser:hotmart.producer||hotmart.name,description:hotmart.description,trackingLink:hotmart.hotlink,category:hotmart.category}} lang={lang} slug={slug}/>;}const campaign=impact.find(c=>c.status==='Active'&&c.trackingLink&&slugify(c.name)===slug);if(!campaign)notFound();return <GenericImpactOfferLanding campaign={campaign} lang={lang} slug={slug}/>;}
